name: Minify and Deploy to Minify Branch

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Minify HTML, CSS, JS
      run: |
        npm install html-minifier terser clean-css-cli -g
        html-minifier --input-dir ./ --output-dir ./ --file-ext html --collapse-whitespace --remove-comments
        terser *.js -o . --compress --mangles
        cleancss -o *.css *.css

    - name: Deploy to Minify Branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: minify  
        publish_dir: ./  
